#include<stdio.h>
#include<stdlib.h>

int divisor(int a,int b,int p)
{
 	int j=0,i=0,c,d,k;
 	while(j==0)
 	{
  	    c=a+p*i;
  	    k=c%b;
  	    if(k==0)
  	    {
  		    d=c/b;
  		    return d;
  		    break;
		}
		else
		i++;
	}
}

void remainder(int a[1000],int dega,int b[1000],int degb,int p)
{
    int a1;
    int i,j;
    if(dega>=degb)
    for(i=0;i<200;i++)
    {
        if(i>(dega-degb))
        {
            break;
        }
        else
        {
		 	while(b[degb]==0)
		 	{
			    degb=degb-1;
			}
            a1=divisor(a[dega-i],b[degb],p);
            for(j=0;j<200;j++)
            {
                if(j>degb)
                {
                    break;
                }
                else
                {
                    a[dega-i-j]=a[dega-i-j]-(a1*b[degb-j]); 
		  			a[dega-i-j]=a[dega-i-j]%p;
		  			a[dega-i-j]=a[dega-i-j]+p;
		  			a[dega-i-j]=a[dega-i-j]%p;
                }
            }
        }
    }
}

void gcd(int a[20],int dega,int b[20],int degb,int p)
{
    int c[20],i,n=0,j;
    j=0;
    while(j==0)
    {
	    remainder(a,dega,b,degb,p);
	    n=0;
        i=0;
		while(i<=dega)
		{
 	        if(a[i]==0)
 	     	{
 		   	    n=n+1;
		    }
			i++;
        }
        if(n==dega+1)
        break;
        else
        {
		 	for(i=0;i<20;i++)
		 	{
		 	    c[i]=a[i]%p;
		 	    c[i]=c[i]+p;
		 	    c[i]=c[i]%p;
		 	    a[i]=b[i]%p;
		 	    a[i]=a[i]+p;
		 	    a[i]=a[i]%p;
		 	    b[i]=c[i];
		 	}
	 	}
    }
    /*b是公因式*/
}

void dif(int a[20],int dega,int p)
{
    int i;
    i=0;
    while(i<dega)
    {
	    a[i]=a[i+1]*(i+1);
	    a[i]=a[i]%p;
	    i++;
	}
	a[dega]=0;
}

int deg(int a[20],int degf)
{
 	int i,b;
 	for(i=1;i<degf;i++)
 	{
        if(a[degf-i]!=0)
        {
		    b=degf-i;
            return b;
		}
    }
}

int power(int a,int b)
{
 	int c;
 	if(b==0)
 	{
	    return 1;
	}
 	else if(b==1)
 	{
		return a;
    }
    else
    {
	 	c=a*power(a,b-1);
	 	return c;
    }
}

int qoutient(int a[20],int dega,int b[20],int degb,int p)
{
    int a1,c[20];
    dega=deg(a,dega);
	degb=deg(b,degb);
    int i,j;
    for(i=0;i<20;i++)
    {
 	    c[i]=0;
	}
    for(i=0;i<200;i++)
    {
        while(b[degb]==0)
		{
   		    degb=degb-1;
		}
  		a1=divisor(a[dega-i],b[degb],p);
    	for(j=0;j<200;j++)
     	{
      	    if(j>degb)
       		{
       		    break;
       		}
            else
            {
                a[dega-i-j]=a[dega-i-j]-(a1*b[degb-j]); 
				a[dega-i-j]=a[dega-i-j]%p;
 				a[dega-i-j]=a[dega-i-j]+p;
  				a[dega-i-j]=a[dega-i-j]%p;
   			}
   		}
   		c[dega-degb-i]=a1;
    }
    for(i=0;i<20;i++)
    {
 	    a[i]=c[i];
	}
	/*a是商*/
}

int finite(int a,int p)
{
 	int i=0,b;
 	while(i<p)
 	{
	    b=power(i,p);
	    b=b%p;
	    if(b==a)
	    {
		    return i;
		}
	    i++;
  	}
}

int main(void)
{
    int Fp,degf,f[20],x[1000],y[20],i,j,A[20][20];
    int b[15],c[20],d[20],ans[20][20],n=0,k[20],add[20],s,t,m=0,o=0,test=0,l,final[20][20][20],run[20],p=0,factor[20][20],e[20];
    /*讀取多項式,F*/
    printf("to factorize a monic polynomial f over F which isomorphic to nZ,n is prime\n");
    printf("|F|=__(prime)\n");
    scanf("%d",&Fp);
    printf("deg(f)=__(<15)\n");
    scanf("%d",&degf);
    for(i=0;i<20;i++)
    {
        if(i==degf)
        {
            f[i]=1;
            break;
        }
        else
        {
            printf("__(x^%d)\n",i);
            scanf("%d",&f[i]);
            f[i]=f[i]%Fp;
        }
    }
    /*讀取多項式,F完成*/
    /*製作g到g^p的矩陣*/ 
    for(i=0;i<20;i++)
    {
        if(i==degf)
        {
            break;
        }
        else
        {
            for(j=0;j<1000;j++)
            {
                x[j]=0;
            }
            x[i*Fp]=1;
            for(j=0;j<20;j++)
            {
                if(j>degf)
                {
                    break;
                }
                else
                {
                    y[j]=f[j];
                }
            }
            remainder(x,(Fp*degf),y,degf,Fp);
            for(j=0;j<20;j++)
            {
                if(j==degf)
                {
                    break;
                }
                else
                {
                    A[j][i]=x[j]%Fp;
                    A[j][i]=A[j][i]+Fp;
                    A[j][i]=A[j][i]%Fp;
                }
            }
        }
    }
    /*完成矩陣*/
    for(i=0;i<20;i++)
    {
	    if(i==degf)
	    break;
	    else
	    {
		 	for(j=0;j<20;j++)
		 	if(j==degf)
		 	break;
		 	else
		 	{
			 	printf("%d ",A[i][j]);
    		}
    		printf("\n");
		}
    }
    /*減掉單位矩陣*/
    for(i=0;i<20;i++)
    {
        if(i==degf)
        {
            break;
        }
        else
        { 
            if(A[i][i]==0)
            {
                A[i][i]=Fp-1;
            }
            else
            {
                A[i][i]=A[i][i]-1;
            }
        }
    }
    /*減掉單位矩陣成功*/ 
    /*找kernel*/
    b[0]=0;
    do
    {
        if(b[0]==Fp)
        break;
        else
        {
		 	b[1]=0;
            do
            {
                if(b[1]==Fp)
                break;
                else
                {  
				   	b[2]=0;
                    do
                    {
                        if(b[2]==Fp)
                        break;
                        else
                        {
						 	b[3]=0;
                            do
                            {
                                if(b[3]==Fp)
                                break;
                                else
                                {
								 	b[4]=0;
                                    do
                                    {
                                        if(b[4]==Fp)
                                        break;
                                        else
                                        {
										 	b[5]=0;
                                            do
                                            {
                                                if(b[5]==Fp)
                                                break;
                                                else
                                                {
												 	b[6]=0;
                                                    do
                                                    {
                                                        if(b[6]==Fp)
                                                        break;  
                                                        else
                                                        {
														 	b[7]=0;
                                                            do
                                                            {
                                                                if(b[7]==Fp)
                                                                break;
                                                                else
                                                                {
																 	b[8]=0;
                                                                    do
                                                                    {
                                                                        if(b[8]==Fp)
                                                                        break;
                                                                        else
                                                                        {
																		 	b[9]=0;
                                                                            do
                                                                            {
                                                                                if(b[9]==Fp)
                                                                                break;
                                                                                else
                                                                                {
																				 	b[10]=0;
                                                                                    do
                                                                                    {
                                                                                        if(b[10]==Fp)
                                                                                        break;
                                                                                        else
                                                                                        {
																						 	b[11]=0;
																						 	do                              
																						 	{                               
                                                                                         	    if(b[11]==Fp)
                                                                                        		break;
                                                                                        		else
                                                                                        		{
									 	                     									    b[12]=0;   
									 	                     									    do         
									 	                     									    {          
						  		               														    if(b[12]==Fp)
						  		               														    break;       
						  		               														    else         
						  		               														    {            
																										 	b[13]=0;                    
																										 	do                          
																										 	{                           
																			  		     					    if(b[13]==Fp)      
																			  		     					    break;             
																			  		     					    else               
																			  		     					    {                  
																										 	        b[14]=0;            
																										 	        do                  
																										 	        {                   
 		                                     																		    if(b[14]==Fp)
 		                                     																		    break;
 		                                     																		    else
 		                                     																		    {																										 	
                                                                                                                            for(i=0;i<20;i++)
                                                                                                                            {
                                                                                                                                if(i==degf)
                                                                                                                                break;
                                                                                                                                else
                                                                                                                                d[i]=0;
                                                                                                                            }
                                                                                                                            for(i=0;i<20;i++)
                                                                                                                            {
                                                                                                                                if(i==degf)
                                                                                                                                {
																														 		    if(o==0)
																														 		    {
																									 								    o++;
																									 								    break;
																																	}						    															 		   								    
                                                                                                                                    for(j=0;j<20;j++)
                                                                                                                                    {
                                                                                                                                        if(j==degf)
                                                                                                                                        break;
                                                                                                                                        else
                                                                                                                                        ans[n][j]=b[j];
                                                                                                                                    }
																																	
																														 		    /*開始測試獨立*/ 
    m=0;
    k[0]=0;
    do
    {
        if(k[0]==Fp)
        break;
        else
        {
		 	k[1]=0;
            do
            {
                if(k[1]==Fp)
                break;
                else
                {  
				   	k[2]=0;
                    do
                    {
                        if(k[2]==Fp)
                        break;
                        else
                        {
						 	k[3]=0;
                            do
                            {
                                if(k[3]==Fp)
                                break;
                                else
                                {
								 	k[4]=0;
                                    do
                                    {
                                        if(k[4]==Fp)
                                        break;
                                        else
                                        {
										 	k[5]=0;
                                            do
                                            {
                                                if(k[5]==Fp)
                                                break;
                                                else
                                                {
												 	k[6]=0;
                                                    do
                                                    {
                                                        if(k[6]==Fp)
                                                        break;  
                                                        else
                                                        {
														 	k[7]=0;
                                                            do
                                                            {
                                                                if(k[7]==Fp)
                                                                break;
                                                                else
                                                                {
																 	k[8]=0;
                                                                    do
                                                                    {
                                                                        if(k[8]==Fp)
                                                                        break;
                                                                        else
                                                                        {
																		 	k[9]=0;
                                                                            do
                                                                            {
                                                                                if(k[9]==Fp)
                                                                                break;
                                                                                else
                                                                                {
																				 	k[10]=0;
                                                                                    do
                                                                                    {
                                                                                        if(k[10]==Fp)
                                                                                        break;
                                                                                        else
                                                                                        {
																						 	k[11]=0;
																						 	do                              
																						 	{                               
                                                                                         	    if(k[11]==Fp)
                                                                                        		break;
                                                                                        		else
                                                                                        		{
									 	                     									    k[12]=0;   
									 	                     									    do         
									 	                     									    {          
						  		               														    if(k[12]==Fp)
						  		               														    break;       
						  		               														    else         
						  		               														    {            
																										 	k[13]=0;                    
																										 	do                          
																										 	{                           
																			  		     					    if(k[13]==Fp)      
																			  		     					    break;             
																			  		     					    else               
																			  		     					    {                  
																										 	        k[14]=0;            
																										 	        do                  
																										 	        {                   
 		                                     																		    if(k[14]==Fp)
 		                                     																		    break;
 		                                     																		    else
 		                                     																		    {
																														 	if(m==0)
																														 	{
																													 		    m++;
																													 		    goto first;
																															}
																															for(j=0;j<20;j++)
																															{
														 				 							    					    add[j]=0; 
																															}
																															test=0;
																														 	s=0; 
																														    while(s<degf)
																															{
																							 				   				    t=0;
																																while(t<=n)
																							 				   				    {
																									 				 			    add[s]=add[s]+k[t]*ans[t][s];
																									 				 			    add[s]=add[s]%Fp;
																									 				 			    t++;
																																}
																																if(add[s]==0)
																																{
										 			         								                                        test=test+1;
										 			         								                                        if(test==degf)										 			         								                                        
																														  			{
				 				 			    						                                                                goto ok;																															           	
											 			                  															}
																																}
																																s++;
																															}	
																												        }
																														first:                   
															 												            k[14]++;        
																												    }while(14<=n);        
																												}                           
   																									            k[13]++;        
																			                                }while(13<=n);
																						                }		                                                                   
 											         	                                                k[12]++;                              
																						            }while(12<=n);                                                          
																						        }                                                                             
                                                                                                k[11]++;    
																		                    }while(11<=n);                                                      
                                                                                        }                   
                                                                                        k[10]++;            
                                                                                    }while(10<=n);        
                                                                                }                           
                                                                                k[9]++;                     
                                                                            }while(9<=n);                 
                                                                        }                                   
                                                                        k[8]++;                             
                                                                    }while(8<=n);                         
                                                                }                                           
                                                                k[7]++;                                     
                                                            }while(7<=n);                                 
                                                        }                                                        
                                                        k[6]++;                                             
                                                    }while(6<=n);                                         
                                                }                                                           
                                                k[5]++;                                                     
                                            }while(5<=n);                                                 
                                        }                                                                   
                                        k[4]++;                                                             
                                    }while(4<=n);                                                         
                                }                                                                           
                                k[3]++;                                                                     
                            }while(3<=n);                                                                 
                        }                                                                                   
                        k[2]++;                                                                             
                    }while(2<=n);                                                                         
                }
                k[1]++;
            }while(1<=n);
        }
        k[0]++;
    }while(0<=n);
	printf("%d:",n);
	for(l=0;l<20;l++)
 	{
  	    if(l==degf)
		break;
		else 
		printf("+(%d)x^%d",ans[n][l],l);
	}
 	printf("\n");
  	n=n+1;				             
																														 		    /*獨立測試結束*/ 
																														 		    ok:
                                                                                                                                    break;
                                                                                                                                }
                                                                                                                                else
                                                                                                                                for(j=0;j<20;j++)
                                                                                                                                {
                                                                                                                                    if(j==degf)
                                                                                                                                    break;
                                                                                                                                    else
                                                                                                                                    d[i]=d[i]+A[i][j]*b[j];
                                                                                                                                }
                                                                                                                                if((d[i]%Fp)!=0)
                                                                                                                                break;
                                                                                                                            }
																												        }                   
															 												            b[14]++;        
																												    }while(14<degf);        
																												}                           
   																									            b[13]++;        
																			                                }while(13<degf);
																						                }		                                                                   
 											         	                                                b[12]++;                              
																						            }while(12<degf);                                                          
																						        }                                                                             
                                                                                                b[11]++;    
																		                    }while(11<degf);                                                      
                                                                                        }                   
                                                                                        b[10]++;            
                                                                                    }while(10<degf);        
                                                                                }                           
                                                                                b[9]++;                     
                                                                            }while(9<degf);                 
                                                                        }                                   
                                                                        b[8]++;                             
                                                                    }while(8<degf);                         
                                                                }                                           
                                                                b[7]++;                                     
                                                            }while(7<degf);                                 
                                                        }                                                        
                                                        b[6]++;                                             
                                                    }while(6<degf);                                         
                                                }                                                           
                                                b[5]++;                                                     
                                            }while(5<degf);                                                 
                                        }                                                                   
                                        b[4]++;                                                             
                                    }while(4<degf);                                                         
                                }                                                                           
                                b[3]++;                                                                     
                            }while(3<degf);                                                                 
                        }                                                                                   
                        b[2]++;                                                                             
                    }while(2<degf);                                                                         
                }
                b[1]++;
            }while(1<degf);
        }
        b[0]++;
    }while(0<degf);
    printf("%d",n);
    printf("\n");
    /*找kernel成功*/
    /*n=basis數量*/
    /*交換1到第一項*/
    i=0;
    while(i<n)
    {
        m=0;
	    if(ans[i][0]!=1)
	    {
		    goto change;
		}
 	    j=1;
 	    while(j<degf)
 	    {
	 	    m=m+ans[i][j];
	 	    j++;
		}
		if(m==0)
        {
		    j=0;
 	        while(j<degf)
 	        {
                c[j]=ans[i][j];
        		ans[i][j]=ans[0][j];
        		ans[0][j]=c[j];
        		j++;
	        }
		    break;
		}
		change:
		i++;
 	}
	s=0;
	while(s<n)
	{
        t=0;
	    printf("%d:",s);
	    while(t<degf)
		{
		    printf("+(%d)x^%d",ans[s][t],t);
		    t++;
		}
		s++;
		printf("\n");
    }
    /*ans[i][j],i是第幾個,j是第幾項,第一個是1*/ 
    /*找到所有primary factor*/
    /*i,j,m,s,t,run,final,p,y*/
    m=1;
    i=1;
    while(i<n)
    {
  	    p=0;
        j=0;
        while(j<Fp)
        {
	        o=0;
	   	    while(o<m)
	   	    {
   		        t=0;
    		    s=0;
      			while(s<degf) 
   				{
			        if(m==1)
			    	{
				 		y[degf]=f[degf];
		                y[s]=f[s];
			        }
			    	else
			    	{
				 	    y[s]=final[i-1][o][s];
				    }
   			    	run[s]=ans[i][s];
   			    	s++;
    		    }
      			run[0]=(run[0]+j)%Fp;
        		gcd(y,degf,run,degf,Fp);
         		s=1;
          		while(s<degf)
           		{
	 		        t=t+run[s];		 
		 			s++;
		 	    }
		 	    if(t!=0)
		 	    {
			 		s=0;
			 		while(s<degf)
			 		{
		 		        final[i][p][s]=run[s];
		 		        s++;
				    }
				    p++;
		        }
				o++;    
		    }
			j++;
		}
 	    m=p;
 	    /**/
      	printf("\n");
    	t=0;
    	while(t<m)
    	{
	        printf("%d:",i);
            j=0;
            while(j<degf)
          	{
                printf("+(%d)x^%d",final[i][t][j],j);
                j++;
	        }
			t++;
			printf("\n");
        } 
        /**/
		i++;
    }
    printf("\n");
    for(i=0;i<20;i++)
    {
	    for(j=0;j<20;j++)
	    {
	 	    factor[i][j]=0;
		}
    }
    i=0;
    while(i<m)
    {
	    printf("%d:",i);
        j=0;
        while(j<degf)
        {
	 	    factor[i][j]=final[n-1][i][j];
            printf("+(%d)x^%d",final[n-1][i][j],j);
            j++;
		}
		i++;
		printf("\n");
    }
	printf("%d\n",m); 
    /*找到所有primary factor成功*/
    /*m個,factor[i][j],第i個,第j項*/
    /*找到q*/ 
    /*
    int Fp,degf,f[20],x[1000],y[20],i,j,A[20][20];
    int b[15],c[20],d[20],ans[20][20],n=0,k[20],add[20],s,t,m=0,o=0,test=0,l,final[20][20][20],run[20],p=0,factor[20][20],e[20];
	*/
	s=0;
	while(s<m)
	{
        n=0;
		start:
        for(i=0;i<20;i++)
        {
            c[i]=0;
        	d[i]=0;
        	y[i]=0;
        	run[i]=0;
        }
    	i=0;
    	while(i<degf)
    	{
 	        c[i]=factor[s][i];
 	        i++;
   		}
   		dif(c,degf,Fp);
   		o=0;
   		i=0;
   		while(i<degf)
   		{
 		    o=o+c[i];
  			i++;
		}
		if(o==0)
		{
		    i=0;
		    while(i<degf)
		    {
	            if(i-(i/Fp)*Fp==0)
	   		    {
			        o=factor[s][i];
	   		    	o=finite(o,Fp);
			   		factor[s][i]=0;
	   		    	factor[s][i/Fp]=o;
				}
			   	i++;
			}
		    n++;
		    goto start;
		}
		else
		{
		 	i=0;
		 	while(i<degf)
		 	{
	 		    d[i]=factor[s][i];
			    i++;
			}
			gcd(d,degf,c,degf,Fp);
			p=0;
			i=1;
			while(i<degf)
			{
	 		    p=p+c[i];
	 		    i++;
			} 
			if(p==0)
			{
 		        e[s]=power(Fp,n);
			}
			else
			{
			 	i=0;
			 	while(i<degf)
			 	{
 			        run[i]=factor[s][i];
 			        i++;
				}
			 	i=0;
			 	while(i<degf)
			 	{
 			        d[i]=factor[s][i];
 			        i++;
				}
			 	qoutient(d,degf,c,degf,Fp);
			 	i=0;
    			while(i<degf)
			 	{
 			        factor[s][i]=d[i];
 			        i++;
				}
				o=power(Fp,n);
			 	e[s]=deg(run,degf)/deg(d,degf)*(Fp^n);
			}
		}
   		s++;
    }
    /*結束!!!!!!!!!!!!!!!!爽!!!!!!!!!!!!!!*/
    i=0;
    while(i<m)
    {
  	    j=1;
  	    while(j<degf)
  	    {
	 	    if(factor[i][degf-j]!=0)
            {
		        o=degf-j;
		        p=factor[i][o];
		        o=divisor(1,p,Fp);
		        break;
		    }
		    j++;
		}
  	    j=0;
  	    while(j<degf)
  	    {
	 	    factor[i][j]=factor[i][j]*o;
	 	    factor[i][j]=factor[i][j]%Fp;
	 	    j++;
		}
  	    i++;
	}
    printf("\n\n");
    i=0;
    while(i<m)
    {
	    printf("%d:",i);
        j=0;
        while(j<degf)
        {
	 	    printf("+(%d)x^%d",factor[i][j],j);
            j++;
		}
		printf("  %d\n",e[i]);
		i++;
    }
    printf("\n\n");
    system("pause");
    return 0;
}
